name: flutter_ecosphere
description: Flutter ecosphere
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # 服务器提供
  shelf: ^1.4.1
  # MySQL
  mysql1: ^0.20.0
  #随机字符串生成
  uuid: 4.2.2
  #加密工具
  crypto: ^3.0.3
  #状态管理
  provider: ^6.0.5




# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

